Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/xenial64"
	# Run Ansible from the Vagrant VM
	config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end